### PR TITLE
Rename "No Action is Required" to "Nope, not right now."

### PR DESCRIPTION
**Pull request by glennj**
Before:
review_action_before
After:
review_action_after

### CODE REVIEW

**Comment by yyyc514** [comment]
It was intentional, though I've been meaning to change the verbiage - so it simply doesn't contridict the prior statement.

**Comment by yyyc514** [comment]
Screen Shot 2020-04-06 at 2 27 19 PM

Gave it a hover underline too for a bit more discoverability.  I'd totally consider moving this to the right hand side above the conversation if we didn't already overload that with SO much stuff (think auto-analysis stuff)

**Comment by yyyc514** [comment]
Or was your original issue actually with contrast?  Always helps to first define what you're trying to solve before showing the solution you came up with. :-)

**Comment by glennj** [comment]
> Or was your original issue actually with contrast? 

It's an invisible button. If I wasn't already familiar with the page, I'd have no idea that I was supposed to click on that. It's just two contradicting sentences: the Monty Python argument sketch.

I have the same thoughts about hover-only style: if it's not obvious that I'm supposed to click on something, why would I put my mouse pointer on it?

**Comment by yyyc514** [comment]
>  It's just two contradicting sentences: the Monty Python argument sketch.

Oh for sure I had realized that. :)  Just hadn't fixed it - until now.

> although the different colour is a hint

Exactly.   I think the new wording helps. I don't believe all buttons or links must look like buttons.

**Comment by yyyc514** [comment]
Screen Shot 2020-04-06 at 8 03 25 PM

I came around a bit, for now.

**Pull request closed without merging**
