### PR TITLE
In discussions, make login name replacement optional.

### PR DESCRIPTION
**Pull request by glennj**
Also, in some pages, don't remove the student role.
* if you're looking at someone else's review for that solution's UUID, both the student and mentor names are redacted. In such case it's harder to tell who's who.

### CODE REVIEW

**Comment by yyyc514** [comment]
For redacted the student label should disappear leading the Mentor labels... how is this not already 100% clear?

**Comment by yyyc514** [comment]
What is your objection to real names vs logins?

**Comment by glennj** [comment]
I find it jarring to see "[Redacted] Mentor" and plain "[Redacted]". I guess I'm not seeing the purpose of removing the role at all.

**Comment by glennj** [comment]
My objection is being labelled as "Josh G.". Until there's a config panel, it'll be a pain to have the config file in source control if my copy is different from your.

**Comment by yyyc514** [comment]
>  I guess I'm not seeing the purpose of removing the role at all.

I'm a big believer in less is more and extraneous elements add clutter.  In 99% of my conversations it's me and the student and those labels provider no value at all.

Redacted is such an edge case that I think I agree with you there though - we can just leave all the label alone in that case...

**Comment by yyyc514** [comment]
> My objection is being labelled as "Josh G.". Until there's a config panel, it'll be a pain to have the config file in source control if my copy is different from your.

Oh yeah, duh. :-)  Soon the real name stuff will all be profile based and I won't be hard-coded, so it'll fetch your name from your profile - that is going to solve itself.

**Comment by glennj** [comment]
> I'm a big believer in less is more and extraneous elements add clutter. In 99% of my conversations it's me and the student and those labels provide no value at all.

This is true.

**Comment by yyyc514** [comment]
Resolved via https://github.com/yyyc514/exercism_plus/commit/5e7465a44d76f3b43ed794fc0edd9a27359db447

**Comment by yyyc514** [comment]
You can set your name now in localstorage or not and it'll keep username... so effectively nothing changes if you don't configure it - so that solves your other issue with becoming me lol

**Pull request closed without merging**
